# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e00492b12da0d8cfd5c67e7d2132fbe84414da4cc87b81c0cc5797e79b1c6a40938a9180f63a88f42a7be8d0174cb7ca1b545a1230a9b135b83365553c3a276

test:
  secret_key_base: 66c8b1027e7b05838c9512e646f180568fb42f0eb7b8969239945cfe9f6be347492d3f3f74057dd5d609fa65ba78d9076ea89d76aebfa448118b095647d1bf4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
